name: GoStatix

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [ '1.18', '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
